### ISSUE TITLE
Gem release?

### ISSUE THREAD

**Issue by wmene** [jpstroop/osullivan#42]
Any plans to push this to rubygems any time soon?  It would make deployment of some apps I'm using MUCH easier :-)

**Comment by jpstroop** [comment]
Sure: https://rubygems.org/gems/osullivan

Some of it is still a bit of a mess, but I think everything safely round-trips, so if it's useful to you I'm happy to put it out. This is my first solo Ruby project, BTW, so feedback is more than welcome!

**Comment by wmene** [comment]
Thanks!

**Comment by jpstroop** [comment]
Glad it's useful :wink:
